// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARvrWZlX5V21j3JGZc0mHXK8MYBYKrqhw',
    appId: '1:670442884979:web:994497f0905b2337d07f06',
    messagingSenderId: '670442884979',
    projectId: 'student-registration-app-b356d',
    authDomain: 'student-registration-app-b356d.firebaseapp.com',
    storageBucket: 'student-registration-app-b356d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4HG3vufyg5r5NKVsFYDcRIl-QKCrbDPE',
    appId: '1:670442884979:android:0c2df9e7f2acb718d07f06',
    messagingSenderId: '670442884979',
    projectId: 'student-registration-app-b356d',
    storageBucket: 'student-registration-app-b356d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW5yZnE64Q461-rMOD06gNDK5jOrcDx2o',
    appId: '1:670442884979:ios:af046dc78201941bd07f06',
    messagingSenderId: '670442884979',
    projectId: 'student-registration-app-b356d',
    storageBucket: 'student-registration-app-b356d.appspot.com',
    iosClientId: '670442884979-5mc21ln4v0cpr7j9rs9k0dlnrsqu2hjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentRegistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW5yZnE64Q461-rMOD06gNDK5jOrcDx2o',
    appId: '1:670442884979:ios:af046dc78201941bd07f06',
    messagingSenderId: '670442884979',
    projectId: 'student-registration-app-b356d',
    storageBucket: 'student-registration-app-b356d.appspot.com',
    iosClientId: '670442884979-5mc21ln4v0cpr7j9rs9k0dlnrsqu2hjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentRegistApp',
  );
}
